Update ci-cd-test-main.yml

diff --git a/.github/workflows/ci-cd-test-main.yml b/.github/workflows/ci-cd-test-main.yml
--- a/.github/workflows/ci-cd-test-main.yml
+++ b/.github/workflows/ci-cd-test-main.yml
@@ -132,7 +132,7 @@ jobs:
 
             # Merge SERVER_BRANCH into TARGET_BRANCH
             git checkout \$TARGET_BRANCH || { echo \\\"❌ Failed to switch back to TARGET_BRANCH\\\"; exit 1; }
-            git merge --no-commit --no-ff \$SERVER_BRANCH || { echo \\\"❌ Failed to merge SERVER_BRANCH into TARGET_BRANCH\\\"; exit 1; }
+            git merge --no-commit --no-ff origin\$SERVER_BRANCH || { echo \\\"❌ Failed to merge SERVER_BRANCH into TARGET_BRANCH\\\"; exit 1; }
           else
             echo \\\"⚠️ SERVER_BRANCH is empty, skipping related operations.\\\";
           fi
