Update ci-cd-test-main.yml

diff --git a/.github/workflows/ci-cd-test-main.yml b/.github/workflows/ci-cd-test-main.yml
--- a/.github/workflows/ci-cd-test-main.yml
+++ b/.github/workflows/ci-cd-test-main.yml
@@ -21,7 +21,7 @@ defaults:
 
 jobs:
   build:
-    runs-on: ubuntu-22.05
+    runs-on: ubuntu-22.04
 
     steps:
       - name: Checkout code
@@ -103,6 +103,7 @@ jobs:
           set -x  
           echo \"✅ TARGET_BRANCH is: $TARGET_BRANCH\"
           echo \"✅ SERVER_BRANCH is: $SERVER_BRANCH\"
+
           docker exec -e TARGET_BRANCH=\"$TARGET_BRANCH\" -e SERVER_BRANCH=\"$SERVER_BRANCH\" sep-erp-test_app_test_1 bash -c \"set -e;
 
           echo \\\"📌 [START] Fetching branches for SERVER_BRANCH: \$SERVER_BRANCH on TARGET_BRANCH: \$TARGET_BRANCH\\\";
@@ -112,7 +113,6 @@ jobs:
 
           git fetch --all || { echo \\\"❌ Failed to fetch branches\\\"; exit 1; }
           git reset --hard origin/\$TARGET_BRANCH || { echo \\\"❌ Failed to reset TARGET_BRANCH\\\"; exit 1; }
-
           git switch \$TARGET_BRANCH || { echo \\\"❌ Failed to switch to TARGET_BRANCH\\\"; exit 1; }
 
           # Ensure the local SERVER_BRANCH is deleted before pulling from remote
@@ -128,16 +128,13 @@ jobs:
           git fetch origin \$SERVER_BRANCH || { echo \\\"❌ Failed to fetch SERVER_BRANCH\\\"; exit 1; }
           git reset --hard origin/\$SERVER_BRANCH || { echo \\\"❌ Failed to reset SERVER_BRANCH\\\"; exit 1; }
 
-          # Merge SERVER_BRANCH into TARGET_BRANCH
-          git checkout \$TARGET_BRANCH || { echo \\\"❌ Failed to switch back to TARGET_BRANCH\\\"; exit 1; }
-          git merge --no-commit --no-ff origin/\$SERVER_BRANCH || { echo \\\"❌ Failed to merge SERVER_BRANCH into TARGET_BRANCH\\\"; exit 1; }
-
-          pnpm run migrate:up
           pnpm i || { echo \\\"❌ Failed to install dependencies\\\"; exit 1; }
           pnpm run build || { echo \\\"❌ Failed to build site\\\"; exit 1; }
+
           echo \\\"📌 [COMPLETE] Server operations finished successfully!\\\";
-          
-          \" || { echo \"❌ Docker exec command failed\"; exit 1; }
+          \" ' || { echo \"❌ Docker exec command failed\"; exit 1; }
+
+
           echo \\\"🔄 Restarting Docker container...\\\"
           docker restart sep-erp-test_app_test_1 2>&1 | tee /tmp/docker_restart.log || { echo \"❌ Failed to restart Docker container\"; cat /tmp/docker_restart.log; exit 1; }
           '"
