Update ci-cd-test-main.yml

diff --git a/.github/workflows/ci-cd-test-main.yml b/.github/workflows/ci-cd-test-main.yml
--- a/.github/workflows/ci-cd-test-main.yml
+++ b/.github/workflows/ci-cd-test-main.yml
@@ -72,9 +72,43 @@ jobs:
 
           # Switch to main/canary branch
           git checkout ${TARGET_BRANCH} || { echo "Failed to checkout ${TARGET_BRANCH}"; exit 1; }
-          echo 'ss'
-          echo "${TARGET_BRANCH}"
-          echo 'ss'
+
+          # Switch to CLIENT_BRANCH or create from remote
+          if git checkout ${CLIENT_BRANCH}; then
+            echo "Switched to existing branch '${CLIENT_BRANCH}'."
+          else
+            echo "'${CLIENT_BRANCH}' does not exist locally. Creating from remote."
+            git checkout -b ${CLIENT_BRANCH} origin/${CLIENT_BRANCH} || { echo "Failed to create branch ${CLIENT_BRANCH}"; exit 1; }
+          fi
+
+          # Pull latest changes into CLIENT_BRANCH
+          git pull origin ${CLIENT_BRANCH} || { echo "Failed to pull ${CLIENT_BRANCH}"; exit 1; }
+
+          # Switch back to TARGET_BRANCH
+          git checkout ${TARGET_BRANCH} || { echo "Failed to checkout ${TARGET_BRANCH}"; exit 1; }
+
+          # Set Git User
+          git config --global user.email "rgjoyce111@gmail.com"
+          git config --global user.name "atomant1969"
+
+          # Merge CLIENT_BRANCH into TARGET_BRANCH without committing
+          git merge ${CLIENT_BRANCH} --no-commit || { echo "Failed to merge ${CLIENT_BRANCH} into ${TARGET_BRANCH}"; exit 1; }
+
+          # Check current directory and contents
+          echo "Current directory:"
+          pwd
+          echo "Directory contents:"
+          ls -la
+
+          # Check pnpm installation
+          echo "Checking pnpm version:"
+          pnpm --version
+
+          # Build site
+          pnpm i || { echo "Failed to install dependencies"; exit 1; }
+          pnpm run build || { echo "Failed to build site"; exit 1; }
+          rsync -av build/ dist/ || { echo "Failed to sync build to dist"; exit 1; }
+          EOF
           
           EOF
 
