Update ci-cd-test-main.yml

diff --git a/.github/workflows/ci-cd-test-main.yml b/.github/workflows/ci-cd-test-main.yml
--- a/.github/workflows/ci-cd-test-main.yml
+++ b/.github/workflows/ci-cd-test-main.yml
@@ -136,9 +136,9 @@ jobs:
           
 
           echo \\\"📌 [COMPLETE] Server operations finished successfully!\\\";
-          '\"  || { echo \"❌ Docker exec command failed\"; exit 1; }
+          \" ' || { echo \"❌ Docker exec command failed\"; exit 1; }
 
-          echo \"🔄 Restarting Docker container...\"
+          echo \\\"🔄 Restarting Docker container...\\\"
           docker restart sep-erp-test_app_test_1 2>&1 | tee /tmp/docker_restart.log || { echo \"❌ Failed to restart Docker container\"; cat /tmp/docker_restart.log; exit 1; }
           '"
 
