Update ci-cd-test-main.yml

diff --git a/.github/workflows/ci-cd-test-main.yml b/.github/workflows/ci-cd-test-main.yml
--- a/.github/workflows/ci-cd-test-main.yml
+++ b/.github/workflows/ci-cd-test-main.yml
@@ -267,15 +267,15 @@ jobs:
         if: always()      
         run: ls -lah allure-reports || echo "⚠️ No reports found in allure-reports"
 
-      - name: Update index.html to point to latest report
-        if: always()      
-        run: |
-          LATEST_DIR=$(ls -td allure-reports/* | head -n 1)
-          sudo chmod -R 777 /home/runner/work/autotests/autotests/allure-reports/index.html || echo "⚠️ Failed to change permissions"
-          echo "<meta http-equiv='refresh' content='0; URL=/index.html'>" > allure-reports/index.html
-          echo "<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate'>" >> allure-reports/index.html
-          echo "<meta http-equiv='Pragma' content='no-cache'>" >> allure-reports/index.html
-          echo "<meta http-equiv='Expires' content='0'>" >> allure-reports/index.html
+      #- name: Update index.html to point to latest report
+       # if: always()      
+       # run: |
+       #   LATEST_DIR=$(ls -td allure-reports/* | head -n 1)
+         # sudo chmod -R 777 /home/runner/work/autotests/autotests/allure-reports/index.html || echo "⚠️ Failed to change permissions"
+         # echo "<meta http-equiv='refresh' content='0; URL=/index.html'>" > allure-reports/index.html
+        #  echo "<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate'>" >> allure-reports/index.html
+        #  echo "<meta http-equiv='Pragma' content='no-cache'>" >> allure-reports/index.html
+        #  echo "<meta http-equiv='Expires' content='0'>" >> allure-reports/index.html
 
      # - name: Force GitHub Pages Refresh
      #   if: always()      
